M48
; DRILL file {KiCad 9.0.6} date 2026-05-15T00:55:19+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-15T00:55:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X625.187Y-355.21
X625.187Y-360.99
T2
X578.75Y-373.25
X603.9Y-304.25
X628.9Y-373.25
M30
