#ifndef DEBUG_PERIPHERALS_H_
#define DEBUG_PERIPHERALS_H_


// User LED
#define ULED_PORT GPIOC
#define ULED_PIN GPIO_PIN_9

#define ULED_ON HAL_GPIO_WritePin(ULED_PORT, ULED_PIN, GPIO_PIN_SET);
#define ULED_OFF HAL_GPIO_WritePin(ULED_PORT, ULED_PIN, GPIO_PIN_RESET);
#define ULED_TOGGLE HAL_GPIO_TogglePin(ULED_PORT, ULED_PIN);

// User button
#define UBTN_PORT GPIOC
#define UBTN_PIN GPIO_PIN_8

#define UBTN_READ HAL_GPIO_ReadPin(UBTN_PORT, UBTN_PIN);


#endif /* DEBUG_PERIPHERALS_H_ */
