#ifndef PARACHUTE_CONTROL_H_
#define PARACHUTE_CONTROL_H_


#define PARA_DEPLOY_PORT GPIOA
#define PARA_DEPLOY_PIN GPIO_PIN_0

#define PARA_DEPLOY_ON HAL_GPIO_WritePin(PARA_DEPLOY_PORT, PARA_DEPLOY_PIN, GPIO_PIN_SET);
#define PARA_DEPLOY_OFF HAL_GPIO_WritePin(PARA_DEPLOY_PORT, PARA_DEPLOY_PIN, GPIO_PIN_RESET);


#endif /* PARACHUTE_CONTROL_H_ */
