#ifndef PINCONFIG_H_
#define PINCONFIG_H_


// Debug peripherals
#define ULED1_PORT GPIOC
#define ULED1_PIN GPIO_PIN_9

#define ULED1_ON HAL_GPIO_WritePin(ULED1_PORT, ULED1_PIN, GPIO_PIN_SET);
#define ULED1_OFF HAL_GPIO_WritePin(ULED1_PORT, ULED1_PIN, GPIO_PIN_RESET);
#define ULED1_TOGGLE HAL_GPIO_TogglePin(ULED1_PORT, ULED1_PIN);

#define UBTN1_PORT GPIOC
#define UBTN1_PIN GPIO_PIN_8

#define UBTN1_READ HAL_GPIO_ReadPin(UBTN1_PORT, UBTN1_PIN)


// LAMBDA62 pins
#define L62_CS_PORT GPIOA
#define L62_CS_PIN GPIO_PIN_15

#define L62_DIO1_PORT GPIOB
#define L62_DIO1_PIN GPIO_PIN_4

#define L62_DIO2_PORT GPIOC
#define L62_DIO2_PIN GPIO_PIN_2

#define L62_BUSY_PORT GPIOB
#define L62_BUSY_PIN GPIO_PIN_5

#define L62_RST_PORT GPIOC
#define L62_RST_PIN GPIO_PIN_13

#define L62_RXSW_PORT GPIOC
#define L62_RXSW_PIN GPIO_PIN_0

#define L62_TXSW_PORT GPIOC
#define L62_TXSW_PIN GPIO_PIN_1


// LAMBDA80 pins
#define L80_CS_PORT GPIOD
#define L80_CS_PIN GPIO_PIN_2

#define L80_DIO1_PORT GPIOB
#define L80_DIO1_PIN GPIO_PIN_6

#define L80_DIO2_PORT GPIOC
#define L80_DIO2_PIN GPIO_PIN_3

#define L80_BUSY_PORT GPIOB
#define L80_BUSY_PIN GPIO_PIN_7

#define L80_RST_PORT GPIOC
#define L80_RST_PIN GPIO_PIN_14



// ADXL375 pins
#define ADXL_CS_PORT GPIOA
#define ADXL_CS_PIN GPIO_PIN_4

#define ADXL_INT1_PORT GPIOB
#define ADXL_INT1_PIN GPIO_PIN_0

#define ADXL_INT2_PORT GPIOB
#define ADXL_INT2_PIN GPIO_PIN_1


// BMP581 pins
#define BMP_INT_PORT GPIOA
#define BMP_INT_PIN GPIO_PIN_11


// LSM6DSR pins
#define LSM6_CS_PORT GPIOA
#define LSM6_CS_PIN GPIO_PIN_3

#define LSM6_INT1_PORT GPIOC
#define LSM6_INT1_PIN GPIO_PIN_4

#define LSM6_INT2_PORT GPIOC
#define LSM6_INT2_PIN GPIO_PIN_5


// MAX-M10S pins
#define M10S_RST_PORT GPIOA
#define M10S_RST_PIN GPIO_PIN_12


// MMC5983MA pins
#define MMC_INT_PORT GPIOA
#define MMC_INT_PIN GPIO_PIN_10


// W25Q pins
#define W25Q_CS_PORT GPIOC
#define W25Q_CS_PIN GPIO_PIN_6

#define W25Q_WP_PORT GPIOC
#define W25Q_WP_PIN GPIO_PIN_7   // MUST BE HELD HIGH TO ALLOW WRITES TO STATUS REGISTER

#define W25Q_HOLD_PORT GPIOB
#define W25Q_HOLD_PIN GPIO_PIN_12   // MUST BE HELD HIGH TO ALLOW COMMUNICATIONS


// Parachute control
#define PARA_DEPLOY_PORT GPIOA
#define PARA_DEPLOY_PIN GPIO_PIN_0

#define PARA_DEPLOY_ON HAL_GPIO_WritePin(PARA_DEPLOY_PORT, PARA_DEPLOY_PIN, GPIO_PIN_SET);
#define PARA_DEPLOY_OFF HAL_GPIO_WritePin(PARA_DEPLOY_PORT, PARA_DEPLOY_PIN, GPIO_PIN_RESET);




#endif /* PINCONFIG_H_ */
