#ifndef DEBUG_PERIPHERALS_H_
#define DEBUG_PERIPHERALS_H_


// User LED
#define ULED1_PORT GPIOC
#define ULED1_PIN GPIO_PIN_9

#define ULED1_ON HAL_GPIO_WritePin(ULED1_PORT, ULED1_PIN, GPIO_PIN_SET);
#define ULED1_OFF HAL_GPIO_WritePin(ULED1_PORT, ULED1_PIN, GPIO_PIN_RESET);
#define ULED1_TOGGLE HAL_GPIO_TogglePin(ULED1_PORT, ULED1_PIN);

#define ULED2_PORT GPIOA
#define ULED2_PIN GPIO_PIN_3

#define ULED2_ON HAL_GPIO_WritePin(ULED2_PORT, ULED2_PIN, GPIO_PIN_SET);
#define ULED2_OFF HAL_GPIO_WritePin(ULED2_PORT, ULED2_PIN, GPIO_PIN_RESET);
#define ULED2_TOGGLE HAL_GPIO_TogglePin(ULED2_PORT, ULED2_PIN);


// User button
#define UBTN1_PORT GPIOC
#define UBTN1_PIN GPIO_PIN_8

#define UBTN1_READ HAL_GPIO_ReadPin(UBTN1_PORT, UBTN_PIN)

#define UBTN2_PORT GPIOA
#define UBTN2_PIN GPIO_PIN_5

#define UBTN2_READ HAL_GPIO_ReadPin(UBTN2_PORT, UBTN_PIN)


#endif /* DEBUG_PERIPHERALS_H_ */
