#ifndef PINCONFIG_H_
#define PINCONFIG_H_


// Debug peripherals
#define ULED1_PORT GPIOC
#define ULED1_PIN GPIO_PIN_9

#define ULED1_ON HAL_GPIO_WritePin(ULED1_PORT, ULED1_PIN, GPIO_PIN_SET);
#define ULED1_OFF HAL_GPIO_WritePin(ULED1_PORT, ULED1_PIN, GPIO_PIN_RESET);
#define ULED1_TOGGLE HAL_GPIO_TogglePin(ULED1_PORT, ULED1_PIN);

#define ULED2_PORT GPIOA
#define ULED2_PIN GPIO_PIN_3

#define ULED2_ON HAL_GPIO_WritePin(ULED2_PORT, ULED2_PIN, GPIO_PIN_SET);
#define ULED2_OFF HAL_GPIO_WritePin(ULED2_PORT, ULED2_PIN, GPIO_PIN_RESET);
#define ULED2_TOGGLE HAL_GPIO_TogglePin(ULED2_PORT, ULED2_PIN);

#define UBTN1_PORT GPIOC
#define UBTN1_PIN GPIO_PIN_8

#define UBTN1_READ HAL_GPIO_ReadPin(UBTN1_PORT, UBTN_PIN)

#define UBTN2_PORT GPIOA
#define UBTN2_PIN GPIO_PIN_5

#define UBTN2_READ HAL_GPIO_ReadPin(UBTN2_PORT, UBTN_PIN)


// LAMBDA62 pins
#define L62_CS_PORT GPIOA
#define L62_CS_PIN GPIO_PIN_15

#define L62_DIO1_PORT GPIOB
#define L62_DIO1_PIN GPIO_PIN_4

#define L62_DIO2_PORT GPIOC
#define L62_DIO2_PIN GPIO_PIN_2

#define L62_BUSY_PORT GPIOB
#define L62_BUSY_PIN GPIO_PIN_5

#define L62_RST_PORT GPIOC
#define L62_RST_PIN GPIO_PIN_13

#define L62_RXSW_PORT GPIOC
#define L62_RXSW_PIN GPIO_PIN_0

#define L62_TXSW_PORT GPIOC
#define L62_TXSW_PIN GPIO_PIN_1


// LAMBDA80 pins
#define L80_CS_PORT GPIOD
#define L80_CS_PIN GPIO_PIN_2

#define L80_DIO1_PORT GPIOB
#define L80_DIO1_PIN GPIO_PIN_6

#define L80_DIO2_PORT GPIOC
#define L80_DIO2_PIN GPIO_PIN_3

#define L80_BUSY_PORT GPIOB
#define L80_BUSY_PIN GPIO_PIN_7

#define L80_RST_PORT GPIOC
#define L80_RST_PIN GPIO_PIN_14










#endif /* PINCONFIG_H_ */
